### ISSUE TITLE
biryani is the best 

### ISSUE THREAD

**Issue by Hammadmirza** [DRuggeri/ScratchSpace#13]
Biryani

**Comment by DRuggeri** [comment]
You're right... Biryani is good, but what does that have to do with our project?

**Comment by Hammadmirza** [comment]
food is important

**Comment by DRuggeri** [comment]
Yes. Yes, it is. But our project is  just a list of lists. Is there a particular list we should update to declare the greatness of biryani?

**Comment by Hammadmirza** [comment]
Please add more toppings.

**Comment by DRuggeri** [comment]
Opening back up - Aaron really needs to fix this.
